# Generated by Django 4.0 on 2022-04-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_address_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['created_at']},
        ),
    ]
