# Generated by Django 3.2.6 on 2021-09-10 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام کتاب')),
                ('author', models.CharField(max_length=200, verbose_name='نویسنده')),
                ('genre', models.CharField(max_length=200, verbose_name='ژانر')),
                ('inventory', models.PositiveIntegerField(default=1, verbose_name='موجودی')),
                ('price', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='قیمت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ افزودن کتاب')),
                ('percent_discount', models.FloatField(default=0, verbose_name='تخفیف درصدی')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='محصولات')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
