# Generated by Django 4.0 on 2022-04-28 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_book_options_book_height_image_book_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='products',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
