# Generated by Django 4.0 on 2022-04-28 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_book_products_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('familly', models.CharField(max_length=200, verbose_name='نام خانوادگی')),
                ('birthday', models.DateField(blank=True, verbose_name='زاد روز')),
                ('country', models.CharField(max_length=200, verbose_name='ملیت')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.author', verbose_name='نویسنده'),
        ),
    ]
