# Generated by Django 4.0 on 2022-04-28 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_author_alter_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
    ]
