# Generated by Django 4.0 on 2022-04-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_name_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='percent_discount',
            field=models.FloatField(default=1, verbose_name='تخفیف درصدی'),
        ),
    ]
