# Generated by Django 4.0 on 2022-04-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_book_percent_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='height_image',
        ),
        migrations.RemoveField(
            model_name='book',
            name='width_image',
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='book',
            name='percent_discount',
            field=models.FloatField(default=0, verbose_name='تخفیف درصدی'),
        ),
    ]
